import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Annotated, Any

import httpx
import typer


app = typer.Typer(help="Agent Secret Hub CLI")

DEFAULT_SERVER = os.getenv("AGENT_SECRET_SERVER", "http://127.0.0.1:8000")
CONFIG_PATH = Path(
    os.getenv("AGENT_SECRET_CONFIG", "~/.agent-secret-hub/config.json")
).expanduser()

AGENT_ENV_PATHS = {
    "hermes": Path.home() / ".hermes" / ".env",
    "openclaw": Path.home() / ".openclaw" / ".env",
    "codex": Path.home() / ".codex" / ".env",
}

AUTO_UPDATE_STAMP = ".agent-secret-last-update"
AUTO_UPDATE_DONE = False


def load_config() -> dict[str, str]:
    if not CONFIG_PATH.exists():
        return {"server": DEFAULT_SERVER}
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def save_config(config: dict[str, str]) -> None:
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(config, indent=2), encoding="utf-8")


def server_url() -> str:
    return load_config().get("server", DEFAULT_SERVER).rstrip("/")


def auth_headers() -> dict[str, str]:
    config = load_config()
    token = config.get("token")
    if not token:
        raise typer.BadParameter("Not logged in. Run: agent-secret login")
    return {"Authorization": f"Bearer {token}"}


def request(method: str, path: str, **kwargs: Any) -> httpx.Response:
    url = f"{server_url()}{path}"
    try:
        response = httpx.request(method, url, timeout=20, **kwargs)
        response.raise_for_status()
        return response
    except httpx.HTTPStatusError as exc:
        detail = exc.response.text
        try:
            detail = exc.response.json().get("detail", detail)
        except ValueError:
            pass
        typer.echo(f"HTTP {exc.response.status_code}: {detail}", err=True)
        raise typer.Exit(1) from exc
    except httpx.RequestError as exc:
        typer.echo(f"Request failed: {exc}", err=True)
        raise typer.Exit(1) from exc


def parse_json_object(raw: str) -> dict[str, Any]:
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise typer.BadParameter(f"Invalid JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise typer.BadParameter("--data must be a JSON object")
    return value


def env_key(*parts: str) -> str:
    raw = "_".join(parts)
    key = re.sub(r"[^A-Za-z0-9]+", "_", raw).strip("_").upper()
    return key


def env_value(value: Any) -> str:
    if isinstance(value, (dict, list)):
        value = json.dumps(value, ensure_ascii=False)
    raw = str(value)
    if re.fullmatch(r"[A-Za-z0-9_./:@%+=,\-]*", raw):
        return raw
    escaped = raw.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def flatten_sync_payload(payload: dict[str, dict[str, Any]]) -> dict[str, str]:
    lines = {}
    for secret_name, data in payload.items():
        for field, value in data.items():
            lines[env_key(secret_name, field)] = env_value(value)
    return dict(sorted(lines.items()))


def write_env_file(path: Path, payload: dict[str, dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    flattened = flatten_sync_payload(payload)
    content = ["# Generated by Agent Secret Hub"]
    content.extend(f"{key}={value}" for key, value in flattened.items())
    path.write_text("\n".join(content) + "\n", encoding="utf-8")


def auto_update_client() -> None:
    global AUTO_UPDATE_DONE
    if AUTO_UPDATE_DONE:
        return
    AUTO_UPDATE_DONE = True

    if os.getenv("AGENT_SECRET_AUTO_UPDATE", "1").lower() in {"0", "false", "no"}:
        return

    repo = Path(__file__).resolve().parents[1]
    if not (repo / ".git").exists():
        return

    interval = int(os.getenv("AGENT_SECRET_AUTO_UPDATE_INTERVAL", "300"))
    stamp = repo / AUTO_UPDATE_STAMP
    now = time.time()
    if stamp.exists() and now - stamp.stat().st_mtime < interval:
        return

    timeout = int(os.getenv("AGENT_SECRET_AUTO_UPDATE_TIMEOUT", "15"))
    commands = [
        ["git", "-C", str(repo), "fetch", "origin", "main"],
        ["git", "-C", str(repo), "checkout", "main"],
        ["git", "-C", str(repo), "reset", "--hard", "origin/main"],
        [sys.executable, "-m", "pip", "install", "-e", str(repo)],
    ]

    try:
        for command in commands:
            subprocess.run(
                command,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
                timeout=timeout,
                check=True,
            )
        stamp.touch()
    except Exception:
        stamp.touch()


@app.callback()
def main() -> None:
    auto_update_client()


@app.command()
def login(
    name: Annotated[str, typer.Option(prompt=True, help="Device name")],
    server: Annotated[str, typer.Option(help="Agent Secret Hub server URL")] = DEFAULT_SERVER,
) -> None:
    response = httpx.post(
        f"{server.rstrip('/')}/device/register",
        json={"name": name},
        timeout=20,
    )
    try:
        response.raise_for_status()
    except httpx.HTTPStatusError as exc:
        typer.echo(exc.response.text, err=True)
        raise typer.Exit(1) from exc

    data = response.json()
    save_config(
        {
            "server": server.rstrip("/"),
            "device_name": name,
            "device_id": data["device_id"],
            "token": data["token"],
        }
    )
    typer.echo(f"Logged in as {name}")


@app.command("set")
def set_secret(
    name: Annotated[str, typer.Argument(help="Secret name, for example OPENAI")],
    data: Annotated[str, typer.Option("--data", help="JSON object payload")],
    secret_type: Annotated[str, typer.Option("--type", help="Secret type")] = "generic",
) -> None:
    payload = {"name": name, "type": secret_type, "data": parse_json_object(data)}
    request("POST", "/secrets", json=payload)
    typer.echo(f"Saved secret {name}")


@app.command("get")
def get_secret(
    name: Annotated[str, typer.Argument(help="Secret name")],
) -> None:
    response = request("GET", f"/secrets/{name}", headers=auth_headers())
    typer.echo(json.dumps(response.json(), indent=2, ensure_ascii=False))


@app.command()
def allow(
    device: Annotated[str, typer.Argument(help="Device name")],
    secret: Annotated[str, typer.Argument(help="Secret name")],
    permission: Annotated[str, typer.Option("--permission")] = "read",
) -> None:
    request(
        "POST",
        "/device/allow",
        json={"device": device, "secret": secret, "permission": permission},
    )
    typer.echo(f"Allowed {device} -> {secret} ({permission})")


@app.command()
def revoke(
    device: Annotated[str, typer.Argument(help="Device name")],
) -> None:
    request("POST", "/device/revoke", json={"device": device})
    typer.echo(f"Revoked {device}")


@app.command()
def sync(
    target: Annotated[
        str,
        typer.Argument(help="all, hermes, openclaw, or codex"),
    ] = "all",
) -> None:
    response = request("GET", "/sync", headers=auth_headers())
    payload = response.json()
    targets = list(AGENT_ENV_PATHS) if target == "all" else [target.lower()]

    for agent in targets:
        if agent not in AGENT_ENV_PATHS:
            raise typer.BadParameter("target must be one of: all, hermes, openclaw, codex")
        write_env_file(AGENT_ENV_PATHS[agent], payload)
        typer.echo(f"Wrote {AGENT_ENV_PATHS[agent]}")


@app.command()
def audit(limit: Annotated[int, typer.Option("--limit")] = 100) -> None:
    response = request("GET", f"/audit?limit={limit}")
    typer.echo(json.dumps(response.json(), indent=2, ensure_ascii=False))


@app.command()
def devices() -> None:
    response = request("GET", "/device")
    typer.echo(json.dumps(response.json(), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    auto_update_client()
    app()
